<?php

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

function tp_product_image_flipper_register_settings() {
	$args = array(
		'type'              => 'integer',
		'sanitize_callback' => 'absint',
		'default'           => 0,
	);

	register_setting( 'tp_product_image_flipper_settings', 'remove_duplicate_images', $args );
	register_setting( 'tp_product_image_flipper_settings', 'images_from_gallery_only', $args );
	register_setting( 'tp_product_image_flipper_settings', 'add_product_link_to_image', $args );
}

add_action( 'admin_init', 'tp_product_image_flipper_register_settings' );

function tp_product_image_flipper_settings_page() {
?>
	<div class="wrap">
		<h1><?php echo esc_html( TP_PRODUCT_IMAGE_FLIPPER_NAME ); ?></h1>
		<form method="post" action="options.php">
			<?php settings_fields( 'tp_product_image_flipper_settings' ); ?>
			<?php do_settings_sections( 'tp_product_image_flipper_settings' ); ?>
			<table class="form-table">
				<tr valign="top">
					<th scope="row"><?php esc_html_e( 'Remove Duplicate Images', 'tp-product-image-flipper-for-woocommerce' ); ?></th>
					<td><input type="checkbox" name="remove_duplicate_images" value="1" <?php checked( 1, get_option( 'remove_duplicate_images' ), true ); ?> /></td>
					<td><?php esc_html_e( 'If checked, this option will remove any additional images of a product in the shop/category pages, showing only the ones generated by the plugin.', 'tp-product-image-flipper-for-woocommerce' ); ?></td>
				</tr>
				<tr valign="top">
					<th scope="row"><?php esc_html_e( 'Images From Gallery Only', 'tp-product-image-flipper-for-woocommerce' ); ?></th>
					<td><input type="checkbox" name="images_from_gallery_only" value="1" <?php checked( 1, get_option( 'images_from_gallery_only' ), true ); ?> /></td>
					<td><?php esc_html_e( 'If checked, this option will use only images from the product gallery for the image flipper. If there are less than two images in the gallery, it will show the product main image.', 'tp-product-image-flipper-for-woocommerce' ); ?></td>
				</tr>
				<tr valign="top">
					<th scope="row"><?php esc_html_e( 'Add Product Link to Images', 'tp-product-image-flipper-for-woocommerce' ); ?></th>
					<td><input type="checkbox" name="add_product_link_to_image" value="1" <?php checked( 1, get_option( 'add_product_link_to_image' ), true ); ?> /></td>
					<td><?php esc_html_e( 'If checked, this option will add the product link to the image. In some themes the product link is removed from the image for a certain reason, if this happens to you, activate this option.', 'tp-product-image-flipper-for-woocommerce' ); ?></td>
				</tr>
			</table>
			<?php submit_button(); ?>
		</form>
	</div>
<?php
}

function tp_product_image_flipper_menu() {
	add_options_page(
		'TP Product Image Flipper Settings',
		'TP Product Image Flipper',
		'manage_options',
		'tp-product-image-flipper',
		'tp_product_image_flipper_settings_page'
	);
}

add_action( 'admin_menu', 'tp_product_image_flipper_menu' );
